build: false


environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_USERNAME: "francescalted"
    CONAN_LOGIN_USERNAME: "francescalted"
    CONAN_CHANNEL: "stable"
    CONAN_UPLOAD: "https://api.bintray.com/conan/blosc/Conan"

    APPVEYOR_RDP_PASSWORD: "wT6s0D54IhKJ$Q5GJhzKs"
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 9
          CONAN_RUN_TESTS: "1"

install:
  - ps: if($env:CONAN_VISUAL_VERSIONS -eq "9") { .\appveyor\vs2008_x86-64_patch\setup_x64.bat }
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools==0.19.3

test_script:
  - python build.py

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
